services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: spells-api-db
      PGDATA: /data/postgres

volumes:
  db:
