services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: spells-api-db
      PGDATA: /data/postgres
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    ports:
      - 8080:8080
    volumes:
      - ./openapi:/openapi

volumes:
  db:
  openapi:
